In [ ]:
# 라이브러리, 데이터
import streamlit as st
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from pathlib import Path
import koreanize_matplotlib

df = pd.read_csv("C:/Users/SBA/Downloads/kobis_20072026.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 24241 entries, 0 to 24240
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   순번      24241 non-null  int64
 1   영화명     24241 non-null  str
 2   감독      20223 non-null  str
 3   제작사     8246 non-null   str
 4   수입사     12870 non-null  str
 5   배급사     24204 non-null  str
 6   개봉일     24240 non-null  str
 7   영화유형    24241 non-null  str
 8   영화형태    24238 non-null  str
 9   국적      24241 non-null  str
 10  전국      24241 non-null  str
 11  전국.1    24220 non-null  str
 12  전국.2    24241 non-null  str
 13  서울      24214 non-null  str
 14  서울.1    24241 non-null  str
 15  장르      24110 non-null  str
 16  등급      24239 non-null  str
 17  영화구분    24241 non-null  str
dtypes: int64(1), str(17)
memory usage: 7.8 MB

In [ ]:
# 분석방향성과 다른 데이터 확인
df["장르"].value_counts()
print( sum( df["장르"].isna() ) )
print( sum( df["장르"].isnull() ) )
df[ df["장르"] != "성인물(에로)" ].info()

131
131
<class 'pandas.DataFrame'>
Index: 18379 entries, 0 to 24240
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   순번      18379 non-null  int64
 1   영화명     18379 non-null  str
 2   감독      16518 non-null  str
 3   제작사     6498 non-null   str
 4   수입사     10640 non-null  str
 5   배급사     18353 non-null  str
 6   개봉일     18378 non-null  str
 7   영화유형    18379 non-null  str
 8   영화형태    18379 non-null  str
 9   국적      18379 non-null  str
 10  전국      18379 non-null  str
 11  전국.1    18358 non-null  str
 12  전국.2    18379 non-null  str
 13  서울      18352 non-null  str
 14  서울.1    18379 non-null  str
 15  장르      18248 non-null  str
 16  등급      18377 non-null  str
 17  영화구분    18379 non-null  str
dtypes: int64(1), str(17)
memory usage: 6.1 MB

In [ ]:
df["영화형태"].value_counts() # 유의미하나 데이터 미비
df["영화유형"].value_counts() # 단일값
df["영화구분"].value_counts() # 단일값

영화구분
일반영화       18063
독립/예술영화     6178
Name: count, dtype: int64

In [ ]:
for col in df.columns[2:-1]:
    if type(col) == str:
        print(col)
        print( df[col].unique() )
        print("="*80)

# 순번, 감독, 제작사, 수입사, 배급사는 유의미하지 않을 것으로 판단.
# 개봉일 데이터타입은 단순 문자열(숫자 사이를 '-'으로 구분)
# 영화유형은 전부 개봉영화, 영화구분은 전부 일반영화
# 영화형태, 영화구분에 'nan'이 결측치가 아닌 입력값으로 존재
# 장르가 "성인물(에로)"인 데이터와 결측치인 데이터는 이상치로 판단.
# 10.전국: 전국 스크린수
# 11.전국.1: 전국 매출액
# 12.전국.2: 전국 관객수
# 13.서울: 서울 매출액
# 14.서울.1: 서울 관객수

감독
<ArrowStringArray>
[        '김한민',         '장항준',         '이병헌',         '김용화',         '윤제균',
 '안소니 루소,조 루소', '크리스 벅,제니퍼 리',     '제임스 카메론',         '류승완',         '김성수',
 ...
         '카즈야',          '도희',         '이주이',         '이지연',         '김소리',
   '그레고리 하타나카',   '알렉세이 시도로프',      '오카다 히로',         '허재형',       '레 탄 선']
Length: 8326, dtype: str
================================================================================
제작사
<ArrowStringArray>
[                           '(주)빅스톤픽쳐스',
                 '(주)온다웍스,(주)비에이엔터테인먼트',
       '(주)어바웃잇,영화사 해그림 주식회사,(주)씨제이이엔엠',
               '리얼라이즈픽쳐스(주),(주)덱스터스튜디오',
                  '(주)제이케이필름,(주)씨제이이엔엠',
                                    nan,
                        '이십세기폭스필름코퍼레이션',
                      '(주)외유내강,(주)필름케이',
                          '(주)하이브미디어코프',
                             '(주)케이퍼필름',
 ...
                            '(주)데이드림서울',
                     '(주)룬컴퍼니,영화사 산들바람',
                              '(주)플라이어',
                 '영화사 레드카펫,주식회사 루믹스미디어',
                           '(주)영화사단막극장',
                               'JK스튜디오',
                              '자작나무영화사',
                        '주식회사 게티스버그컴퍼니',
                         '(주)스카이라이프티브이',
 '디멘션 필름즈,스펙타클 엔터테인먼트 그룹,트랜카스 인태내셔널 필름']
Length: 2578, dtype: str
================================================================================
수입사
<ArrowStringArray>
[                        nan,        '월트디즈니컴퍼니코리아 유한책임회사',
 '주식회사 해리슨앤컴퍼니,이십세기폭스코리아(주)',            '월트디즈니컴퍼니코리아(주)',
  '소니픽쳐스릴리징월트디즈니스튜디오스코리아(주)',             '워너브러더스 코리아(주)',
              '이십세기폭스코리아(주)',         '롯데컬처웍스(주)롯데엔터테인먼트',
  '소니픽쳐스엔터테인먼트코리아주식회사극장배급지점',                 '(주)씨제이이엔엠',
 ...
                '(주)빅마운틴컬쳐스',                 '영화사마농주식회사',
                 '주식회사 락희상회',    '위드 라이언 픽쳐스,(주)도키엔터테인먼트',
                       'S&S',                '(주)디에이치미디어',
             '퍼즐컷,(유)조이앤시네마',                  '(주)메이크아트',
                       '하드릴',                 '레인주니어 픽쳐스']
Length: 812, dtype: str
================================================================================
배급사
<ArrowStringArray>
[                            '(주)씨제이이엔엠',
                                '(주)쇼박스',
                         '롯데쇼핑㈜롯데엔터테인먼트',
                    '월트디즈니컴퍼니코리아 유한책임회사',
             '주식회사 해리슨앤컴퍼니,이십세기폭스코리아(주)',
                 '메가박스중앙(주) 플러스엠 엔터테인먼트',
                   '(주)넥스트엔터테인먼트월드(NEW)',
 '주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트',
                     '롯데컬처웍스(주)롯데엔터테인먼트',
                             '씨제이엔터테인먼트',
 ...
                             '주식회사 락희상회',
                              '㈜스튜디오오르카',
                '위드 라이언 픽쳐스,(주)도키엔터테인먼트',
                                   'S&S',
                             '(유)헤이데이웍스',
                               '(주)달빛공장',
                              '(주)해머픽쳐스',
                                '(주)오예스',
                                   '하드릴',
                         '주식회사 게티스버그컴퍼니']
Length: 1594, dtype: str
================================================================================
개봉일
<ArrowStringArray>
['2014-07-30', '2026-02-04', '2019-01-23', '2017-12-20', '2014-12-17',
 '2019-04-24', '2019-11-21', '2009-12-17', '2015-08-05', '2023-11-22',
 ...
 '2023-08-19', '2023-01-29', '2024-02-17', '2022-08-21', '2023-06-27',
 '2023-03-26', '2017-05-20', '2017-12-17', '2023-09-25', '2024-01-29']
Length: 3976, dtype: str
================================================================================
영화유형
<ArrowStringArray>
['개봉영화']
Length: 1, dtype: str
================================================================================
영화형태
<ArrowStringArray>
['장편', '옴니버스', '단편', nan, '온라인전용', '기타']
Length: 6, dtype: str
================================================================================
국적
<ArrowStringArray>
[         '한국',          '미국',          '일본',          '영국',          '중국',
         '프랑스',         '벨기에',          '독일',          '홍콩',          '인도',
       '아이슬란드',         '캐나다',         '스페인',         '러시아',        '아일랜드',
          '태국',    '남아프리카공화국',          '대만',         '핀란드',         '스웨덴',
         '멕시코',        '이탈리아',        '네덜란드',          '호주',         '덴마크',
          '기타',       '아르헨티나',         '헝가리',          '페루',        '노르웨이',
       '우크라이나',       '인도네시아',       '오스트리아',          '터키',        '이스라엘',
          '이란',         '베트남',        '뉴질랜드',         '스위스',          '체코',
         '그리스',         '폴란드',          '칠레',       '말레이시아',         '브라질',
          '소련',          '몽고',        '싱가포르',        '루마니아',        '포르투갈',
        '우루과이',        '보스니아',       '팔레스타인',        '콜롬비아',       '에스토니아',
 '아랍에미리트연합국정부',        '불가리아',         '모로코',          '부탄',       '슬로바키아',
         '필리핀',         '이라크',          '쿠바',       '크로아티아',       '베네수엘라',
       '카자흐스탄',         '이집트',          '몰타',        '세르비아',       '마케도니아',
      '우즈베키스탄']
Length: 71, dtype: str
================================================================================
전국
<ArrowStringArray>
['1,587', '1,724', '1,978', '1,912',   '966', '2,835', '2,648',   '912',
 '1,064', '2,328',
 ...
    '77',     '7',     '4',   '376',   '115',   '369',    '13',     '6',
   '127',     '9']
Length: 1202, dtype: str
================================================================================
전국.1
<ArrowStringArray>
['135,748,398,910', '162,898,938,670', '139,647,979,516', '115,698,654,137',
 '110,828,014,630', '122,182,694,160', '114,810,421,450', '128,447,097,523',
 '105,024,756,250', '127,926,951,712',
 ...
           '4,000',          '25,278',           '3,000',          '15,228',
           '2,000',           '6,091',          '17,600',           '1,000',
           '8,800',           '6,600']
Length: 10547, dtype: str
================================================================================
전국.2
<ArrowStringArray>
['17,613,682', '16,880,990', '16,264,944', '14,410,754', '14,245,998',
 '13,934,592', '13,747,792', '13,624,328', '13,395,400', '13,128,080',
 ...
          '9',          '8',          '7',          '6',          '5',
          '4',          '3',          '2',          '1',          '0']
Length: 8396, dtype: str
================================================================================
서울
<ArrowStringArray>
['33,121,225,810', '34,840,190,620', '31,858,660,536', '27,530,825,087',
 '25,842,519,330', '33,577,136,860', '28,824,682,580', '40,547,523,000',
 '26,766,369,950', '29,336,875,104',
 ...
        '105,000',         '91,000',         '98,000',         '49,000',
         '29,000',         '15,000',         '17,600',         '17,000',
          '8,800',          '6,600']
Length: 9866, dtype: str
================================================================================
서울.1
<ArrowStringArray>
['4,163,666', '3,494,144', '3,638,287', '3,346,172', '3,233,946', '3,597,963',
 '3,225,974', '3,993,374', '3,290,366', '2,956,518',
 ...
    '33,468',        '18',         '9',        '13',        '33',         '6',
        '39',        '24',        '44',        '35']
Length: 7426, dtype: str
================================================================================
장르
<ArrowStringArray>
[      '사극',      '코미디',      '판타지',      '드라마',       '액션',    '애니메이션',
       'SF',       '범죄',     '어드벤처',     '미스터리',       '전쟁', '서부극(웨스턴)',
   '멜로/로맨스',      '스릴러',    '다큐멘터리',   '공포(호러)',      '뮤지컬',       '가족',
       '기타',       '공연',  '성인물(에로)',        nan]
Length: 22, dtype: str
================================================================================
등급
<ArrowStringArray>
[         '15세이상관람가',          '12세이상관람가',             '전체관람가',
           '청소년관람불가',  '청소년관람불가,15세이상관람가',            '12세관람가',
            '15세관람가',    '12세이상관람가,전체관람가', '12세이상관람가,15세이상관람가',
            '18세관람가',    '15세이상관람가,전체관람가',   '연소자관람불가,청소년관람불가',
             '제한상영가',                 nan,   '15세관람가,12세이상관람가']
Length: 15, dtype: str
================================================================================

In [ ]:
# 데이터 추출 가능성 확인
df_ticket = df.copy()
df_ticket = df_ticket[df_ticket["장르"] != "성인물(에로)"]

target_columns = ["전국", "전국.1", "전국.2", "서울", "서울.1"]

# 지정한 모든 열의 콤마를 제거하고 int형으로 변환
df_ticket = df_ticket.dropna(axis=0, subset=["전국.1", "서울"] )
for col in target_columns:
    df_ticket[col] = df_ticket[col].str.replace(",", "", regex=True).astype(int)

df_ticket = df_ticket.drop( df_ticket[ df_ticket["전국.1"] == 0 ].index )
df_ticket = df_ticket.drop( df_ticket[ df_ticket["서울"] == 0 ].index )

df_ticket.info()

# 부가가치세 10%, 영화발전기금 3%, 남은 87%를 극장과 배급사가 50:50
# "전국.1" / 전국.2 /0.83 / 0.5 = 해당영화의 해당연도 평균 티켓값
df_ticket["예측티켓값"] = df_ticket["전국.1"] / df_ticket["전국.2"] / 0.83 / 0.5

<class 'pandas.DataFrame'>
Index: 12521 entries, 0 to 24223
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   순번      12521 non-null  int64
 1   영화명     12521 non-null  str
 2   감독      11645 non-null  str
 3   제작사     4609 non-null   str
 4   수입사     7705 non-null   str
 5   배급사     12501 non-null  str
 6   개봉일     12521 non-null  str
 7   영화유형    12521 non-null  str
 8   영화형태    12521 non-null  str
 9   국적      12521 non-null  str
 10  전국      12521 non-null  int64
 11  전국.1    12521 non-null  int64
 12  전국.2    12521 non-null  int64
 13  서울      12521 non-null  int64
 14  서울.1    12521 non-null  int64
 15  장르      12471 non-null  str
 16  등급      12521 non-null  str
 17  영화구분    12521 non-null  str
dtypes: int64(6), str(12)
memory usage: 3.9 MB

In [ ]:
df_ticket["예측티켓값"].describe()

count     12521.000000
mean      18202.110427
std        8655.705929
min          16.046130
25%       14491.911871
50%       17966.232767
75%       20248.821372
max      168674.698795
Name: 예측티켓값, dtype: float64

In [ ]:
df_ticket.sort_values("예측티켓값")

,순번,영화명,감독,제작사,수입사,배급사,개봉일,영화유형,영화형태,국적,전국,전국.1,전국.2,서울,서울.1,장르,등급,영화구분,예측티켓값
1686,1687,인플루언스,이재규,"리얼라이즈픽쳐스(주),윈저엔터테인먼트",NaN,NaN,2010-08-19,개봉영화,장편,한국,3,1529006,229610,1310000,175,드라마,15세이상관람가,일반영화,16.046130
1679,1680,원스,존 카니,NaN,"(주)제이앤씨미디어그룹,(주)영화사 진진","(주)제이앤씨미디어그룹,와이드 릴리즈(주),(주)영화사 진진",2007-09-20,개봉영화,장편,아일랜드,10,45419094,232459,44139500,180826,드라마,전체관람가,독립/예술영화,470.808186
4816,4817,추적자,무로가 아츠시,NaN,스크린조이,스크린조이,2014-03-06,개봉영화,장편,일본,5,6310000,10502,520000,104,범죄,청소년관람불가,일반영화,1447.802255
5300,5301,워리어스 레인보우: 항전의 시작,위덕성,NaN,스크린조이,스크린조이,2014-02-20,개봉영화,장편,대만,5,5070000,7640,950000,190,드라마,청소년관람불가,일반영화,1599.066423
6166,6167,거짓말 섹스가 좋아2,진달래,(주)케이알씨지,NaN,(주)케이알씨지,2013-12-24,개봉영화,장편,한국,5,2980000,4490,500000,100,멜로/로맨스,청소년관람불가,일반영화,1599.270132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3470,3471,엔하이픈 브이알콘서트 : 이머전,김경국,(주)어메이즈브이알코리아,NaN,(주)어메이즈브이알코리아,2025-08-08,개봉영화,장편,한국,1,945066000,29022,945066000,29022,드라마,전체관람가,일반영화,78466.937836
10328,10329,밀라노 두오모 콘서트,리카르도 샤이,NaN,일미디어,일미디어,2022-01-07,개봉영화,장편,이탈리아,6,6469200,190,4699700,137,공연,전체관람가,일반영화,82044.388079
6263,6264,앤팀 브이알 콘서트 : 바운드리스,김경국,(주)어메이즈브이알코리아,NaN,(주)어메이즈브이알코리아,2026-06-26,개봉영화,장편,한국,1,151404000,4207,151404000,4207,드라마,전체관람가,일반영화,86719.495047
7239,7240,요루시카 '달과 고양이의 댄스' 2024 라이브,NaN,NaN,NaN,씨제이 씨지브이(CJ CGV)(주),2024-11-29,개봉영화,장편,일본,3,108339000,2211,89376000,1824,공연,전체관람가,일반영화,118072.289157
9696,9697,러비타 퍼스트 팬 콘서트 <어웨이크닝>,NaN,NaN,NaN,씨제이포디플렉스 주식회사,2025-11-15,개봉영화,장편,한국,1,23730000,339,23730000,339,공연,전체관람가,일반영화,168674.698795

In [ ]:
# 날짜 -> 타임스탬프 변환
df_date = pd.DataFrame({"raw_date": df_ticket["개봉일"] })
df_date["clean_date"] = pd.to_datetime(df_date["raw_date"], errors='coerce')

print(df_date)

df_ticket["개봉연도"] = df_date["clean_date"].dt.year.tolist()
df_ticket["개봉월"] = df_date["clean_date"].dt.month.tolist()

df_ticket

         raw_date clean_date
0      2014-07-30 2014-07-30
1      2026-02-04 2026-02-04
2      2019-01-23 2019-01-23
3      2017-12-20 2017-12-20
4      2014-12-17 2014-12-17
...           ...        ...
24106  2021-03-27 2021-03-27
24109  2015-08-05 2015-08-05
24195  2014-04-24 2014-04-24
24203  2010-06-10 2010-06-10
24223  2021-03-26 2021-03-26

[12521 rows x 2 columns]

,순번,영화명,감독,제작사,수입사,배급사,개봉일,영화유형,영화형태,국적,...,전국.1,전국.2,서울,서울.1,장르,등급,영화구분,예측티켓값,개봉연도,개봉월
0,1,명량,김한민,(주)빅스톤픽쳐스,NaN,(주)씨제이이엔엠,2014-07-30,개봉영화,장편,한국,...,135748398910,17613682,33121225810,4163666,사극,15세이상관람가,일반영화,18571.050374,2014,7
1,2,왕과 사는 남자,장항준,"(주)온다웍스,(주)비에이엔터테인먼트",NaN,(주)쇼박스,2026-02-04,개봉영화,장편,한국,...,162898938670,16880990,34840190620,3494144,사극,12세이상관람가,일반영화,23252.638800,2026,2
2,3,극한직업,이병헌,"(주)어바웃잇,영화사 해그림 주식회사,(주)씨제이이엔엠",NaN,(주)씨제이이엔엠,2019-01-23,개봉영화,장편,한국,...,139647979516,16264944,31858660536,3638287,코미디,15세이상관람가,일반영화,20688.737413,2019,1
3,4,신과함께-죄와 벌,김용화,"리얼라이즈픽쳐스(주),(주)덱스터스튜디오",NaN,롯데쇼핑㈜롯데엔터테인먼트,2017-12-20,개봉영화,장편,한국,...,115698654137,14410754,27530825087,3346172,판타지,12세이상관람가,일반영화,19346.103450,2017,12
4,5,국제시장,윤제균,"(주)제이케이필름,(주)씨제이이엔엠",NaN,(주)씨제이이엔엠,2014-12-17,개봉영화,장편,한국,...,110828014630,14245998,25842519330,3233946,드라마,12세이상관람가,일반영화,18745.998486,2014,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24106,24107,2021 첫 섹스,김동해,라이어 시네마,NaN,케이엘 픽쳐스,2021-03-27,개봉영화,장편,한국,...,2000,1,2000,1,멜로/로맨스,청소년관람불가,일반영화,4819.277108,2021,3
24109,24110,2047: 지구 최후의 날,알렉산드로 카폰,NaN,(주)소나무픽쳐스,(주)소나무픽쳐스,2015-08-05,개봉영화,장편,이탈리아,...,8000,1,8000,1,액션,15세이상관람가,일반영화,19277.108434,2015,8
24195,24196,F.O.E.: 에프.오.이.,키오니 왁스먼,NaN,라인트리엔터테인먼트,라인트리엔터테인먼트,2014-04-24,개봉영화,장편,미국,...,2000,1,2000,1,액션,청소년관람불가,일반영화,4819.277108,2014,4
24203,24204,H2: 어느 살인마의 가족이야기,롭 좀비,"디멘션 필름즈,스펙타클 엔터테인먼트 그룹,트랜카스 인태내셔널 필름",(주)누리픽쳐스,(주)누리픽쳐스,2010-06-10,개봉영화,장편,미국,...,8000,1,8000,1,공포(호러),청소년관람불가,일반영화,19277.108434,2010,6
24223,24224,O형수박가슴가정부-무삭제,판,스마일컨텐츠,NaN,스마일컨텐츠,2021-03-26,개봉영화,장편,한국,...,1000,1,1000,1,멜로/로맨스,청소년관람불가,일반영화,2409.638554,2021,3

In [ ]:
for year in range(2017,2027):
    print( df_ticket["예측티켓값"][df_ticket["개봉연도"] == year].describe() )

count      936.000000
mean     15884.000328
std       7073.929332
min       4535.790220
25%      12170.721345
50%      17198.768066
75%      18739.149671
max      59394.582491
Name: 예측티켓값, dtype: float64
count     1006.000000
mean     14852.096219
std       7953.995440
min       2409.638554
25%      11503.108576
50%      17157.380688
75%      19457.463378
max      59082.319845
Name: 예측티켓값, dtype: float64
count      838.000000
mean     16581.674032
std       8776.226812
min       2409.638554
25%      12290.928420
50%      18200.569722
75%      19861.766891
max      72289.156627
Name: 예측티켓값, dtype: float64
count      815.000000
mean     17925.661019
std      10194.623077
min       2409.638554
25%      12048.192771
50%      18818.536409
75%      20507.383924
max      73936.416988
Name: 예측티켓값, dtype: float64
count      937.000000
mean     17504.656143
std       8578.849012
min       2409.638554
25%      12048.192771
50%      18263.835917
75%      21418.014400
max      71834.002677
Name: 예측티켓값, dtype: float64
count      628.000000
mean     21224.365031
std       9062.514971
min       2516.733601
25%      17678.488374
50%      21449.369941
75%      23462.921213
max      82044.388079
Name: 예측티켓값, dtype: float64
count      556.000000
mean     23737.295185
std       8122.427876
min       3855.421687
25%      20389.748140
50%      22192.179434
75%      24001.514832
max      66875.799042
Name: 예측티켓값, dtype: float64
count       548.000000
mean      24157.365181
std       10476.069890
min        9637.121657
25%       19932.804191
50%       21870.196730
75%       23456.575132
max      118072.289157
Name: 예측티켓값, dtype: float64
count       594.000000
mean      24770.760175
std       12207.684820
min        9638.554217
25%       20291.427672
50%       22247.500234
75%       23814.724194
max      168674.698795
Name: 예측티켓값, dtype: float64
count      254.000000
mean     25155.412667
std      10934.068688
min       8483.495936
25%      20700.630526
50%      22416.961500
75%      24735.830944
max      86719.495047
Name: 예측티켓값, dtype: float64

In [ ]:
# 데이터 정제

# 컬럼 제한
target_columns = [ "영화명", "영화형태", "국적", "전국", "전국.1", "전국.2", "서울", "서울.1", "장르", "등급", "예측티켓값", "개봉연도", "개봉월" ]
df_ticket = df_ticket[target_columns]

# "장르"가 "성인물(에로)", "공연", "뮤지컬"인 데이터와 결측치인 데이터는 이상치로 판단, 삭제.
df_ticket = df_ticket[ ~df_ticket["장르"].str.contains("성인물(에로)|공연|뮤지컬", na=False ) ]
df_ticket = df_ticket.dropna(subset=["장르"])

# "예측티켓값"이 10000 미만인 데이터는 이상치로 판단, 삭제.
df_ticket = df_ticket.drop( df_ticket[ df_ticket["예측티켓값"] < 10000 ].index )

# "전국"이 1이하고, "전국.2"가 100 미만인 데이터, 또는 "전국"이 10 이하고, "전국.2"가 50 이하인 데이터는 이상치로 판단, 삭제.
df_ticket = df_ticket.drop( df_ticket[ df_ticket["전국"] <= 10 ][ df_ticket["전국.2"] <= 100 ].index )

# 콘서트, 뮤지컬 제외
df_ticket = df_ticket[ ~df_ticket["영화명"].str.contains("콘서트|뮤지컬", na=False ) ]

# "등급"이 "청소년관람불가"이면서 "장르"가 "멜로/로맨스", "드라마", "기타", "코미디"인 데이터 중 일부를 이상치로 판단, 삭제.
df_ticket = df_ticket.drop( df_ticket[ df_ticket["등급"] == "청소년관람불가" ][ df_ticket["장르"] == "멜로/로맨스" ].index )
df_ticket = df_ticket.drop( df_ticket[ df_ticket["등급"] == "청소년관람불가" ][ df_ticket["장르"] == "드라마" ][ df_ticket["전국"] < 30 ].index )
df_ticket = df_ticket.drop( df_ticket[ df_ticket["등급"] == "청소년관람불가" ][ df_ticket["장르"] == "기타" ][ df_ticket["전국"] < 30 ].index )
df_ticket = df_ticket.drop( df_ticket[ df_ticket["등급"] == "청소년관람불가" ][ df_ticket["장르"] == "코미디" ][ df_ticket["예측티켓값"] < 17000 ].index )

df_ticket

C:\Users\SBA\AppData\Local\Temp\ipykernel_5524\1696977932.py:8: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_ticket = df_ticket[ ~df_ticket["장르"].str.contains("성인물(에로)|공연|뮤지컬", na=False ) ]
C:\Users\SBA\AppData\Local\Temp\ipykernel_5524\1696977932.py:15: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_ticket = df_ticket.drop( df_ticket[ df_ticket["전국"] <= 1 ][ df_ticket["전국.2"] < 100 ].index )
C:\Users\SBA\AppData\Local\Temp\ipykernel_5524\1696977932.py:16: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_ticket = df_ticket.drop( df_ticket[ df_ticket["전국"] <= 10 ][ df_ticket["전국.2"] <= 50 ].index )
C:\Users\SBA\AppData\Local\Temp\ipykernel_5524\1696977932.py:22: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_ticket = df_ticket.drop( df_ticket[ df_ticket["등급"] == "청소년관람불가" ][ df_ticket["장르"] == "멜로/로맨스" ].index )
C:\Users\SBA\AppData\Local\Temp\ipykernel_5524\1696977932.py:23: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_ticket = df_ticket.drop( df_ticket[ df_ticket["등급"] == "청소년관람불가" ][ df_ticket["장르"] == "드라마" ][ df_ticket["전국"] < 30 ].index )
C:\Users\SBA\AppData\Local\Temp\ipykernel_5524\1696977932.py:23: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_ticket = df_ticket.drop( df_ticket[ df_ticket["등급"] == "청소년관람불가" ][ df_ticket["장르"] == "드라마" ][ df_ticket["전국"] < 30 ].index )
C:\Users\SBA\AppData\Local\Temp\ipykernel_5524\1696977932.py:24: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_ticket = df_ticket.drop( df_ticket[ df_ticket["등급"] == "청소년관람불가" ][ df_ticket["장르"] == "기타" ][ df_ticket["전국"] < 30 ].index )
C:\Users\SBA\AppData\Local\Temp\ipykernel_5524\1696977932.py:24: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_ticket = df_ticket.drop( df_ticket[ df_ticket["등급"] == "청소년관람불가" ][ df_ticket["장르"] == "기타" ][ df_ticket["전국"] < 30 ].index )
C:\Users\SBA\AppData\Local\Temp\ipykernel_5524\1696977932.py:25: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_ticket = df_ticket.drop( df_ticket[ df_ticket["등급"] == "청소년관람불가" ][ df_ticket["장르"] == "코미디" ][ df_ticket["예측티켓값"] < 17000 ].index )
C:\Users\SBA\AppData\Local\Temp\ipykernel_5524\1696977932.py:25: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_ticket = df_ticket.drop( df_ticket[ df_ticket["등급"] == "청소년관람불가" ][ df_ticket["장르"] == "코미디" ][ df_ticket["예측티켓값"] < 17000 ].index )

,영화명,영화형태,국적,전국,전국.1,전국.2,서울,서울.1,장르,등급,예측티켓값,개봉연도,개봉월
0,명량,장편,한국,1587,135748398910,17613682,33121225810,4163666,사극,15세이상관람가,18571.050374,2014,7
1,왕과 사는 남자,장편,한국,1724,162898938670,16880990,34840190620,3494144,사극,12세이상관람가,23252.638800,2026,2
2,극한직업,장편,한국,1978,139647979516,16264944,31858660536,3638287,코미디,15세이상관람가,20688.737413,2019,1
3,신과함께-죄와 벌,장편,한국,1912,115698654137,14410754,27530825087,3346172,판타지,12세이상관람가,19346.103450,2017,12
4,국제시장,장편,한국,966,110828014630,14245998,25842519330,3233946,드라마,12세이상관람가,18745.998486,2014,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12382,고골: 악령과의 전쟁,장편,러시아,5,220000,51,84000,28,미스터리,15세이상관람가,10394.519253,2019,10
12675,초능력 에볼루션,장편,미국,19,240900,36,126400,14,SF,15세이상관람가,16124.497992,2021,5
12775,레저렉션 이펙트,장편,기타,21,189940,30,100940,12,SF,청소년관람불가,15256.224900,2021,6
12882,스페이스 시그널,장편,미국,18,118480,24,53540,8,액션,12세이상관람가,11895.582329,2021,5
12892,더 엑시트,장편,미국,18,116500,23,38000,7,판타지,15세이상관람가,12205.343112,2021,6

In [ ]:
df_ticket["예측티켓값"].describe()

count     8787.000000
mean     18942.389962
std       3994.180188
min      10020.570085
25%      17042.773375
50%      18594.966926
75%      20645.523873
max      75849.024674
Name: 예측티켓값, dtype: float64

In [ ]:
# df_ticket[ df_ticket["장르"].str.contains("다큐멘터리", na=False ) ]
# df_ticket[ df_ticket["등급"] == "청소년관람불가" ][ df_ticket["장르"] == "기타" ].sort_values("전국")
df_ticket.sort_values("예측티켓값", ascending=False).tail(60)

,영화명,영화형태,국적,전국,전국.1,전국.2,서울,서울.1,장르,등급,예측티켓값,개봉연도,개봉월
9242,크리미널 트위스트,장편,영국,50,2444000,524,650000,130,액션,15세이상관람가,11238.848524,2022,6
5343,죽이는 여자,장편,미국,1,34371000,7395,1491000,1395,공포(호러),청소년관람불가,11199.687187,2020,8
10753,환생령,장편,말레이시아,5,645000,139,16000,8,공포(호러),12세이상관람가,11181.416313,2018,9
9405,더 워닝,장편,스페인,32,2068500,448,720500,140,스릴러,15세이상관람가,11125.753012,2020,5
9955,애플시드:엑스머시나,장편,일본,1,1204000,261,1204000,261,SF,12세이상관람가,11115.727277,2008,6
11287,불륜관계,장편,중국,6,392000,85,116000,29,멜로/로맨스,15세이상관람가,11112.686038,2016,7
9229,몬스터 아일랜드,장편,미국,50,2452000,532,600000,120,SF,15세이상관람가,11106.078449,2022,4
10808,탐정 당인: 차이나타운 살인사건,장편,중국,1,613000,133,613000,133,액션,15세이상관람가,11106.078449,2018,3
4952,영웅: 천하의 시작,장편,중국,54,44066600,9575,16875000,2228,액션,15세이상관람가,11089.773192,2014,3
9225,데스위시 더 게임,장편,미국,50,2453000,533,600000,120,액션,15세이상관람가,11089.762427,2022,4
7126,독도의 영웅들,장편,한국,4,10933000,2384,10808000,2364,다큐멘터리,12세이상관람가,11050.578152,2016,2
9650,제거자,장편,미국,5,1638000,359,1352000,264,스릴러,청소년관람불가,10994.395409,2015,1
9649,서바이벌 워,장편,미국,6,1638000,359,1366000,266,액션,15세이상관람가,10994.395409,2015,1
11180,엑소시즘: 악령의 눈동자,장편,미국,5,456000,100,100000,20,공포(호러),청소년관람불가,10987.951807,2021,9
9196,마지막 대전투: 전장의 영웅들,장편,미국,50,2466000,546,600000,120,전쟁,15세이상관람가,10883.092811,2022,3
4969,배틀 스쿨,장편,일본,7,42769200,9499,33733800,7387,액션,청소년관람불가,10849.385541,2019,2
9861,첫잔처럼,장편,한국,1,1305000,290,1305000,290,드라마,15세이상관람가,10843.373494,2019,10
8228,분신사바-저주의 시작,장편,중국,20,5299000,1178,1045000,239,스릴러,15세이상관람가,10839.282427,2014,9
8323,자이언트 몽키,장편,미국,20,4982000,1108,1290000,258,스릴러,12세이상관람가,10834.674438,2014,8
8390,신선조-낭인,장편,일본,20,4751000,1057,1085000,253,액션,15세이상관람가,10830.835167,2014,10
8313,815사수작전,장편,한국,10,5005500,1114,3060000,867,코미디,12세이상관람가,10827.150613,2025,8
8391,에이지 오브 다이노소어,장편,미국,20,4743000,1057,1085000,253,SF,15세이상관람가,10812.597599,2014,10
8366,닌자2: 섀도우 어쌔신,장편,미국,20,4823000,1077,1085000,253,액션,청소년관람불가,10790.795494,2014,10
8397,청풍자,장편,홍콩,20,4708000,1052,1090000,258,스릴러,15세이상관람가,10783.819689,2014,10
11478,정 검-금의위,장편,중국,5,313000,70,80000,12,액션,15세이상관람가,10774.526678,2016,9
8382,슈퍼 사이클론 스톰,장편,미국,20,4752000,1064,1020000,204,SF,15세이상관람가,10761.844370,2014,8
11496,쥬라기 파크: 아마존 어드벤쳐,장편,미국,5,302000,68,60000,14,어드벤처,15세이상관람가,10701.630050,2017,3
8396,야쿠자-피의 전쟁,장편,일본,20,4668000,1052,1090000,258,액션,청소년관람불가,10692.198452,2014,10
9524,샌 안드레스 메가 대지진,장편,미국,48,1779000,401,404000,82,액션,12세이상관람가,10690.142115,2022,1
4115,길,장편,한국,54,75398600,17014,10665400,2010,드라마,12세이상관람가,10678.463236,2017,5
10322,수춘도 2: 수라전장,장편,중국,1,845000,191,759000,155,액션,15세이상관람가,10660.442818,2017,11
8230,홈,장편,프랑스,5,5206793,1177,4221000,939,다큐멘터리,전체관람가,10659.718910,2009,6
8220,아틀란틱 머신,장편,미국,20,5261000,1191,1115000,283,SF,12세이상관람가,10644.087686,2014,10
9454,그레이트 샤크2,장편,미국,50,1877000,425,414000,82,액션,12세이상관람가,10642.097803,2021,12
4928,디에고,장편,영국,26,42971500,9738,20093000,5653,다큐멘터리,12세이상관람가,10633.167296,2019,12
9161,FBI 데스트랩,장편,미국,50,2484000,564,600000,120,스릴러,15세이상관람가,10612.663420,2022,3
4711,몽키킹2: 서유기 여정의 시작,장편,중국,54,49077600,11156,9673700,2102,액션,12세이상관람가,10600.508884,2016,5
10313,근거리 연애,장편,일본,1,844000,192,644000,92,멜로/로맨스,15세이상관람가,10592.369478,2017,9
7018,리틀 제이콥,장편,한국,9,11336000,2581,7510000,1710,애니메이션,전체관람가,10583.364065,2012,11
8165,스톰 둠스데이,장편,미국,20,5374000,1237,900000,198,액션,12세이상관람가,10468.389321,2014,10
12235,안드론: 블랙 라비린스,장편,이탈리아,6,233000,54,22000,8,SF,15세이상관람가,10397.144132,2016,10
12382,고골: 악령과의 전쟁,장편,러시아,5,220000,51,84000,28,미스터리,15세이상관람가,10394.519253,2019,10
9552,살인의 기억,장편,멕시코,5,1698000,394,1210000,238,SF,15세이상관람가,10384.685952,2014,12
10154,금의위 3인의 무사,장편,중국,20,953000,222,903000,172,액션,15세이상관람가,10344.079019,2021,1
6264,별별 이야기 2-여섯 빛깔 무지개,옴니버스,한국,11,18046500,4205,7842500,1693,가족,12세이상관람가,10341.389339,2008,4
7393,세이브 어 라이프,장편,미국,6,8645263,2017,7057000,1684,드라마,15세이상관람가,10328.189904,2010,11
10994,나는 원래 대전에서 로맨틱 코미디를 찍으려고 했었다,장편,한국,1,497000,116,161000,68,드라마,12세이상관람가,10324.054840,2019,6
5140,카르마,장편,태국,20,36302000,8497,15972500,3762,공포(호러),15세이상관람가,10294.774485,2008,6
9586,넥스트 투모로우 2,장편,미국,4,1626000,381,1096000,216,액션,12세이상관람가,10283.654302,2014,11
9580,에이리언 스페이스,장편,미국,4,1636000,384,846000,166,SF,15세이상관람가,10266.064257,2014,11
11476,영춘백학권,장편,중국,6,297000,70,34000,11,액션,15세이상관람가,10223.752151,2016,10
12323,쿵푸몬스터: 무림괴수전,장편,중국,5,229000,54,93000,31,코미디,12세이상관람가,10218.652387,2019,7
9219,생존게임 247°F,장편,미국,6,2278000,538,990000,198,공포(호러),15세이상관람가,10202.893358,2014,9
5162,무협: 더 코드,장편,미국,1,35376040,8371,2486000,2372,액션,15세이상관람가,10183.188374,2020,6
10791,우리들의 일기,장편,한국,6,570000,135,299000,43,액션,청소년관람불가,10174.029451,2017,6
9598,몬스터 울프,장편,미국,4,1594000,378,804000,160,판타지,12세이상관람가,10161.280041,2014,11
8759,압록강은 흐른다,장편,한국,1,3397814,806,3360500,797,드라마,전체관람가,10158.193070,2009,6
10041,신선조-혈풍,장편,일본,6,1015000,244,555000,139,액션,청소년관람불가,10023.701363,2014,11
10983,후계자,장편,프랑스,34,495000,119,40000,4,스릴러,15세이상관람가,10023.286423,2025,11
8735,포스터,장편,영국,4,3410000,820,2800000,700,가족,전체관람가,10020.570085,2013,12

In [ ]:
df_ticket[ df_ticket["등급"] == "청소년관람불가" ][ df_ticket["장르"] == "코미디" ][ df_ticket["예측티켓값"] < 17000 ]

C:\Users\SBA\AppData\Local\Temp\ipykernel_5524\2920374540.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_ticket[ df_ticket["등급"] == "청소년관람불가" ][ df_ticket["장르"] == "코미디" ][ df_ticket["예측티켓값"] < 17000 ]
C:\Users\SBA\AppData\Local\Temp\ipykernel_5524\2920374540.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_ticket[ df_ticket["등급"] == "청소년관람불가" ][ df_ticket["장르"] == "코미디" ][ df_ticket["예측티켓값"] < 17000 ]

Empty DataFrame
Columns: [영화명, 영화형태, 국적, 전국, 전국.1, 전국.2, 서울, 서울.1, 장르, 등급, 예측티켓값, 개봉연도, 개봉월]
Index: []